# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('college', models.CharField(blank=True, max_length=120, null=True)),
                ('branch', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('contact', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
            ],
        ),
    ]
