# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='SharePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=20)),
                ('time', models.TimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellbuy.Share', to_field='name')),
            ],
        ),
    ]
