# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-30 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0002_auto_20170727_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareprice',
            options={'get_latest_by': 'time'},
        ),
        migrations.AlterField(
            model_name='shareprice',
            name='share',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
