# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0003_auto_20170730_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareprice',
            options={},
        ),
    ]
