# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0004_auto_20170804_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareprice',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellbuy.Share'),
        ),
    ]
