# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=10000.0, max_digits=7)),
            ],
        ),
    ]
