# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='share_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
