# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170725_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
