# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170725_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='share_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
