# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170726_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=120, null=True)),
                ('time', models.TimeField()),
                ('holdings', models.DecimalField(decimal_places=2, default=10000.0, max_digits=20)),
            ],
        ),
    ]
