# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_userholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userholding',
            name='current_holdings',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=20),
        ),
    ]
